# Generated by Django 4.2 on 2023-04-29 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='celular',
            field=models.CharField(default='(xx)xxxxx-xxxx', max_length=15),
        ),
    ]
