# Generated by Django 4.2 on 2023-04-30 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0002_contato_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='celular',
            field=models.CharField(max_length=15),
        ),
    ]
