# Generated by Django 4.2 on 2023-04-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0003_contato_data_alter_contato_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
