# Generated by Django 4.2 on 2023-05-11 02:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0004_alter_contato_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='celular',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(15)]),
        ),
        migrations.AlterField(
            model_name='contato',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='mensagem',
            field=models.TextField(max_length=300),
        ),
    ]
