# Generated by Django 4.2 on 2023-04-21 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=500)),
                ('tipo_veiculo', models.CharField(choices=[('C', 'Carro'), ('M', 'Moto')], max_length=1)),
                ('preco_base', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=150)),
                ('veiculo', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('observacao', models.CharField(blank=True, max_length=300)),
                ('tipo_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.tiposervico')),
            ],
        ),
    ]
