# Generated by Django 4.2 on 2023-05-26 00:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='video'),
        ),
    ]
