# Generated by Django 4.2 on 2023-05-17 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='servico',
            name='tipo_servico',
            field=models.CharField(choices=[('INTERNO', 'Interno'), ('EXTERNO', 'Externo'), ('AMBOS', 'Ambos')], max_length=10, verbose_name='Tipo de serviço'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='tipo_veiculo',
            field=models.CharField(choices=[('C', 'Carro'), ('M', 'Moto')], max_length=1, verbose_name='Tipo de veículo'),
        ),
    ]
