# Generated by Django 4.2 on 2023-04-29 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_promocao', models.DecimalField(decimal_places=2, max_digits=6)),
                ('valido_ate', models.DateField()),
                ('tipo_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.tiposervico')),
            ],
        ),
    ]
