# Generated by Django 4.2 on 2023-05-01 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_promocao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocao',
            options={'verbose_name': 'Promoção', 'verbose_name_plural': 'Promoções'},
        ),
        migrations.AlterModelOptions(
            name='servico',
            options={'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.AlterModelOptions(
            name='tiposervico',
            options={'verbose_name': 'Tipo de serviço', 'verbose_name_plural': 'Tipos de serviço'},
        ),
        migrations.AddField(
            model_name='promocao',
            name='descricao',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='tipo_servico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicos.tiposervico'),
        ),
    ]
